In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.42681449  1.00675698  0.90341368  1.96581842  0.06614455]


In [4]:
print(a.shape) # rank 1 array => 이러한 데이터 구조 비추천

(5,)


In [5]:
print(a.T) # a == a.T

[-0.42681449  1.00675698  0.90341368  1.96581842  0.06614455]


In [6]:
print(np.dot(a, a.T))

5.880703683161997


In [7]:
a = np.random.randn(5,1)
print(a)

[[-1.90538089]
 [-0.93450909]
 [ 0.60206073]
 [ 0.26842597]
 [-1.54150635]]


In [8]:
print(a.T)

[[-1.90538089 -0.93450909  0.60206073  0.26842597 -1.54150635]]


In [9]:
print(np.dot(a, a.T))

[[ 3.63047633  1.78059577 -1.14715501 -0.51145372  2.93715675]
 [ 1.78059577  0.87330725 -0.56263123 -0.25084651  1.44055171]
 [-1.14715501 -0.56263123  0.36247712  0.16160874 -0.92808044]
 [-0.51145372 -0.25084651  0.16160874  0.0720525  -0.41378034]
 [ 2.93715675  1.44055171 -0.92808044 -0.41378034  2.37624184]]


In [14]:
assert(a.shape == (5,1))

In [ ]:
a = a.reshape((5,1))