In [ ]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.9, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.9  52.    8. ]
 [  1.8 135.   99.    0.9]]


In [ ]:
cal = A.sum(axis =0)
print(cal)

[ 59.  239.9 155.4  76.9]


In [ ]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.72655273 33.46203346 10.40312094]
 [ 3.05084746 56.27344727 63.70656371  1.17035111]]
